#!/usr/bin/env bash
# Cursor support for the Simple English hook set. Cursor loads no plugins, so this
# script writes the files that Cursor reads (https://cursor.com/docs/hooks and
# https://cursor.com/docs/context/rules):
#   <project>/.cursor/rules/simple-english.mdc      always-on rules (alwaysApply: true)
#   <project>/.cursor/hooks.json                    four hook entries (merged in)
#   <project>/.cursor/hooks/simple-english-hook.sh  wrapper that calls hooks/cursor.sh
#   <project>/.claude/ste-mode                      per-repo mode, shared with all harnesses
# With --user it writes ~/.cursor/hooks.json plus the global flag instead. The user
# scope has no rule file: Cursor user rules are plain text in the settings, not files.
#
# Usage: bash cursor-install.sh [--project DIR | --user] on|strict|off|status|uninstall
set -u
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WRAP_NAME="simple-english-hook.sh"

usage() {
  printf 'Usage: bash cursor-install.sh [--project DIR | --user] on|strict|off|status|uninstall\n'
  printf '  --project DIR  target project (default: the current directory)\n'
  printf '  --user         target ~/.cursor instead of a project\n'
  exit "${1:-0}"
}

SCOPE="project"; PROJ="$PWD"; CMD=""
while [ $# -gt 0 ]; do
  case "$1" in
    --project) [ $# -ge 2 ] || usage 1; PROJ="$2"; shift 2 ;;
    --user)    SCOPE="user"; shift ;;
    on|strict|off|status|uninstall) CMD="$1"; shift ;;
    -h|--help) usage 0 ;;
    *) printf 'Unknown argument: %s\n' "$1" >&2; usage 1 ;;
  esac
done
[ -n "$CMD" ] || CMD="status"
command -v jq >/dev/null || { printf 'cursor-install.sh needs jq.\n' >&2; exit 1; }

export STE_HARNESS=cursor
if [ "$SCOPE" = "project" ]; then
  [ -d "$PROJ" ] || { printf 'No such project directory: %s\n' "$PROJ" >&2; exit 1; }
  PROJ="$(cd "$PROJ" && pwd)"
  export CLAUDE_PROJECT_DIR="$PROJ"
  CUR="$PROJ/.cursor"
  HOOK_CMD=".cursor/hooks/$WRAP_NAME"
else
  CUR="$HOME/.cursor"
  HOOK_CMD="./hooks/$WRAP_NAME"
fi
source "$ROOT/hooks/common.sh"
HJ="$CUR/hooks.json"
WRAP="$CUR/hooks/$WRAP_NAME"

write_wrapper() {
  mkdir -p "$CUR/hooks"
  {
    printf '#!/usr/bin/env bash\n'
    printf '# %s wrapper. Generated by cursor-install.sh. Do not edit.\n' "$STE_CURSOR_MARK"
    printf '# Keeps the absolute path (with spaces) out of hooks.json.\n'
    printf 'exec bash "%s/hooks/cursor.sh"\n' "$ROOT"
  } > "$WRAP"
  chmod +x "$WRAP"
}

# Merge this plugin's entries into hooks.json. Entries from other tools stay.
write_hooks_json() {
  local tmp
  [ -f "$HJ" ] || { mkdir -p "$CUR"; printf '{"version":1,"hooks":{}}\n' > "$HJ"; }
  tmp="$(mktemp)"
  jq -s --arg cmd "$HOOK_CMD" '
    (.[1].hooks | with_entries(.value |= map(.command = $cmd))) as $ours
    | .[0]
    | .version = (.version // 1)
    | .hooks = (reduce ($ours | to_entries[]) as $e ((.hooks // {});
        .[$e.key] = (((.[$e.key] // []) | map(select(.command | test("simple-english-hook") | not))) + $e.value)))
  ' "$HJ" "$ROOT/hooks/cursor-hooks.json" > "$tmp" && mv "$tmp" "$HJ"
}

# Remove this plugin's entries. Delete the file when nothing else is left in it.
remove_hooks_json() {
  local tmp
  [ -f "$HJ" ] || return 0
  tmp="$(mktemp)"
  jq '
    .hooks = ((.hooks // {})
      | with_entries(.value |= map(select(.command | test("simple-english-hook") | not)))
      | with_entries(select(.value | length > 0)))
  ' "$HJ" > "$tmp" || { rm -f "$tmp"; return 1; }
  if jq -e '(.hooks == {}) and ((keys - ["version","hooks"]) == [])' "$tmp" >/dev/null; then
    rm -f "$HJ" "$tmp"
  else
    mv "$tmp" "$HJ"
  fi
}

set_mode() {
  if [ "$SCOPE" = "project" ]; then ste_set_project_mode "$1"; else ste_set_mode "$1"; fi
}

case "$CMD" in
  on|strict)
    write_wrapper
    write_hooks_json
    set_mode "$CMD"
    if [ "$SCOPE" = "project" ]; then
      ste_cursor_write_rule "$CUR/rules/simple-english.mdc" "$CMD"
      printf 'Wrote %s\n' "$CUR/rules/simple-english.mdc"
    else
      printf 'User scope: no rule file. The rules load at session start only.\n'
    fi
    printf 'Wrote %s and %s\n' "$HJ" "$WRAP"
    printf 'Mode: %s. Cursor reloads hooks.json on save. Restart Cursor if hooks do not load.\n' "$CMD"
    ;;
  off)
    set_mode off
    [ "$SCOPE" = "project" ] && ste_cursor_remove_rule "$CUR/rules/simple-english.mdc"
    printf 'Mode: off. The hook files stay, so /ste on works later. Use uninstall to remove them.\n'
    ;;
  status)
    printf 'harness: cursor  scope: %s\n' "$SCOPE"
    printf 'mode: %s (source: %s)\n' "$(ste_mode)" "$(ste_mode_source)"
    [ "$SCOPE" = "project" ] && printf 'rule file: %s\n' "$([ -f "$CUR/rules/simple-english.mdc" ] && printf 'present' || printf 'absent')"
    printf 'hooks.json entries: %s\n' "$([ -f "$HJ" ] && grep -q simple-english-hook "$HJ" && printf 'present' || printf 'absent')"
    printf 'wrapper: %s\n' "$([ -x "$WRAP" ] && printf 'present' || printf 'absent')"
    ;;
  uninstall)
    remove_hooks_json
    rm -f "$WRAP"
    rmdir "$CUR/hooks" 2>/dev/null || true
    if [ "$SCOPE" = "project" ]; then
      ste_cursor_remove_rule "$CUR/rules/simple-english.mdc"
      rmdir "$CUR/rules" "$CUR" 2>/dev/null || true
      printf 'Removed the Cursor files. %s stays, because other harnesses read it.\n' "$PROJ/.claude/ste-mode"
    else
      rm -f "$STE_FLAG" "$STE_SCORE"
      rm -rf "$STE_STATE_DIR/simple-english-hook"
      printf 'Removed the user-level hooks, the flag, the score file, and the saved replies.\n'
    fi
    ;;
esac
exit 0
